# Generated by Django 4.0.3 on 2022-11-05 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='active_account',
            field=models.BooleanField(default=True, verbose_name='Active Account'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='cui',
            field=models.CharField(default='0', max_length=13, unique=True, verbose_name='CUI'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(default='correo@gmail.com', max_length=150, verbose_name='Correo'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fisrt_name',
            field=models.CharField(default='Nombres', max_length=150, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='last_name',
            field=models.CharField(default='Apellidos', max_length=150, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='login_attempts',
            field=models.IntegerField(default=0, verbose_name='Login Attempts'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='profile_image',
            field=models.ImageField(default='users_pictures/default.png', upload_to='User_Profile_Image', verbose_name='Imagen de Perfil'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='username',
            field=models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=150, verbose_name='Username'),
        ),
    ]
