# Generated by Django 4.0.3 on 2022-11-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuarios_active_account_alter_usuarios_cui_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
