# Generated by Django 4.0.3 on 2022-11-05 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_fisrt_name_usuarios_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='first_name',
            new_name='fisrt_name',
        ),
    ]
