# Generated by Django 4.0.3 on 2022-10-04 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_employee_options_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['id'], 'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
    ]
