# Generated by Django 4.0.3 on 2022-10-04 23:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_alter_employee_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_joined',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Fecha de Registro'),
        ),
    ]
