# Generated by Django 4.0.3 on 2022-10-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_employee_date_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
