# Generated by Django 4.0.3 on 2022-10-04 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_employee_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cvitae',
            field=models.FileField(blank=True, null=True, upload_to='avatar/%Y/%m/%d'),
        ),
    ]
