# Generated by Django 4.0.3 on 2022-10-10 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_remove_product_tall_product_color_product_talla_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cui',
            field=models.CharField(max_length=13, unique=True, verbose_name='CUI'),
        ),
    ]
