# Generated by Django 4.0.3 on 2022-10-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_detsale_estado_alter_detsale_cant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Negro', 'Negro'), ('Gris', 'Gris'), ('Blanco', 'Blanco'), ('Rojo', 'Rojo')], default='Negro', max_length=10, verbose_name='Color'),
        ),
    ]
