# Generated by Django 4.0.3 on 2022-10-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0016_alter_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detsale',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='detsale',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cli',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='DetSale',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
