# Generated by Django 4.0.3 on 2022-11-07 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineapedido',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lineapedido',
            name='operacion',
            field=models.CharField(default='compra', max_length=50),
        ),
    ]
