# Generated by Django 4.0.3 on 2022-10-11 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('Negro', 'Negro'), ('Gris', 'Gris'), ('Blanco', 'Blanco'), ('Rojo', 'Rojo'), ('Azul Marino', 'Azul Marino')], default='Negro', max_length=15, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='talla',
            field=models.CharField(choices=[('39', '39-S'), ('39.5', '39.5-S'), ('40', '40-S'), ('40.5', '40-S'), ('41', '41-S'), ('41.5', '41.5-M'), ('42', '42-M'), ('42.5', '42.5-L'), ('43', '43-L'), ('43.5', '43.5-L'), ('44', '44-XL'), ('44.5', '44.5-XL'), ('45', '45-XL')], default='10', max_length=15, verbose_name='Talla'),
        ),
        migrations.CreateModel(
            name='Tallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(choices=[('39', '39-S'), ('39.5', '39.5-S'), ('40', '40-S'), ('40.5', '40-S'), ('41', '41-S'), ('41.5', '41.5-M'), ('42', '42-M'), ('42.5', '42.5-L'), ('43', '43-L'), ('43.5', '43.5-L'), ('44', '44-XL'), ('44.5', '44.5-XL'), ('45', '45-XL')], default='10', max_length=15, verbose_name='Talla')),
                ('cant', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('nam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Tallas',
                'verbose_name_plural': 'Tallas',
                'ordering': ['id'],
            },
        ),
    ]
