# Generated by Django 4.0.3 on 2022-10-11 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_product_color_alter_product_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='talla',
        ),
    ]
