# Generated by Django 4.0.3 on 2022-11-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_product_categoria_product_disponibilidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tallas',
            name='creacion',
        ),
        migrations.RemoveField(
            model_name='tallas',
            name='update',
        ),
    ]
