# Generated by Django 4.0.3 on 2022-11-05 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_product_image2_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detsale',
            name='prod',
        ),
        migrations.RemoveField(
            model_name='detsale',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='cli',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='DetSale',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
